### ISSUE TITLE
Not working with the HiBeacons demo app

### ISSUE THREAD

**Issue by DigitalRogues** [mttrb/BeaconOSX#1]
I'm not sure if its just an incompatibility or what, but I run your demo app on my mac mini with BT4, and it doesn't get detected by the hiBeacons demo app (https://github.com/nicktoumpelis/HiBeacons), which I'm guessing it should.

I don't have to do anything with your demo app besides run it correct?

peripheralManagerDidUpdateState does get run and it goes throughout he method, creating the beaconData and then using the _manager to start advertising it.

I do have bluetooth in use for a magic trackpad, would that interfere with the beacon advertising?

**Comment by mttrb** [comment]
I suspect the issue is that my code is using a different proximityUUID to the one that HiBeacon is scanning for.  You can change the proximityUUID in the AppDelegate.

The fact you have a MagicPad shouldn't affect anything.

**Comment by DigitalRogues** [comment]
Holy crap I'm an idiot, thanks a ton.  I guess I didn't realize the ID needed to be the same.
