### ISSUE TITLE
Using the source in a paid app

### ISSUE THREAD

**Issue by ghost** [mttrb/BeaconOSX#10]
Hey there, love BeaconOSX and have been playing around with it for a couple days. Would it be possible to include this source code without modification in a paid app I'm working on? Kind of an off topic question, but your permissions section doesn't have a GNU or MIT license, so I thought I would ask :) Thanks!

**Comment by mttrb** [comment]
The code is licensed with the BSD 3-clause license, this is a permissive license. As long as you follow the instructions in the license you can include the BeaconOSX code in a paid app.  

Let me know when you release your app :)
