### ISSUE TITLE
yosemite not supported

### ISSUE THREAD

**Issue by guozheng** [mttrb/BeaconOSX#13]
it seems that OSX 10.10.x was not supported, is this because of the Yosemite itself stops supporting iBeacon? Is this the same issue as MacBeacon's issue with Yosemite? http://www.radiusnetworks.com/ibeacon/macbeacon/

**Comment by mttrb** [comment]
It appears that Apple have closed the loop hole that allowed Mavericks to act as an iBeacon.

**Comment by katzlbt** [comment]
What makes you think that it is a fixed loophole vs. a bug in Yosemite?

Commit for reference to this bug: 8a94eb9b3e0b470fc7f3356f33df68c6d088b769

**Comment by mttrb** [comment]
This was never officially supported in Mavericks.  I don't believe Apple support any iBeacon functionality on OS X.  In Mavericks, it just happened that passing some information generated on an iOS device into CoreBluetooth on OS X worked. 

Given Apple don't support iBeacons on OS X it doesn't surprise me that they've stopped this functionality working in Yosemite.  I'm a little surprised they didn't stop it in a Mavericks point release.

If someone wants to file a radar with Apple then by all means but I certainly won't be holding my breath.
